// app\creator\works\[workId]\chapters\[chapterId]\editor\_components\templates.ts
import { ElementStyle, TemplateId } from "./types";

const BASE_TEXT = {
  fontFamily: "Arial",
  fontStyle: "normal" as const,
  lineHeight: 1.2,
  letterSpacing: 0,
  textFill: "#111111",
  textStroke: undefined as any,
  textStrokeWidth: 0,
  textShadow: undefined as any,
  textRotation: 0,
  fontSizeMode: "auto" as const,
};

export const TEMPLATE_DEFAULT_STYLE: Record<TemplateId, ElementStyle> = {
  bubble_ellipse: {
    fill: "#ffffff",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 22,
    align: "center",
    ...BASE_TEXT,
  },
  bubble_roundrect: {
    fill: "#ffffff",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 22,
    align: "center",
    ...BASE_TEXT,
  },
  bubble_cloud: {
    fill: "#ffffff",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 22,
    align: "center",
    ...BASE_TEXT,
  },
  bubble_burst: {
    fill: "#ffffff",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 22,
    align: "center",
    ...BASE_TEXT,
  },

  narration_rect: {
    fill: "#f7f7f7",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 20,
    align: "center",
    ...BASE_TEXT,
  },
  narration_roundrect: {
    fill: "#f7f7f7",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 20,
    align: "center",
    ...BASE_TEXT,
  },
  caption_box: {
    fill: "#f7f7f7",
    stroke: "#111111",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 20,
    align: "center",
    ...BASE_TEXT,
  },

  scene_label: {
    fill: "#ffffffcc",
    stroke: "#111111",
    strokeWidth: 1,
    opacity: 1,
    fontSize: 18,
    align: "center",
    ...BASE_TEXT,
  },
  signage_label: {
    fill: "#ffffffcc",
    stroke: "#111111",
    strokeWidth: 1,
    opacity: 1,
    fontSize: 18,
    align: "center",
    ...BASE_TEXT,
  },

  sfx_burst: {
    fill: "#00000000",
    stroke: "#ff00ff",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 28,
    align: "center",
    fontFamily: "Impact",
    fontStyle: "bold",
    lineHeight: 1.05,
    letterSpacing: 1,
    textFill: "#111111",
    textStroke: "#ffffff",
    textStrokeWidth: 2,
    textShadow: {
      color: "#000000",
      blur: 6,
      offsetX: 2,
      offsetY: 2,
      opacity: 0.4,
    },
    textRotation: 0,
    fontSizeMode: "auto",
  },
  sfx_outline: {
    fill: "#00000000",
    stroke: "#ff00ff",
    strokeWidth: 2,
    opacity: 1,
    fontSize: 28,
    align: "center",
    fontFamily: "Impact",
    fontStyle: "bold",
    lineHeight: 1.05,
    letterSpacing: 1,
    textFill: "#111111",
    textStroke: "#ffffff",
    textStrokeWidth: 2,
    textShadow: {
      color: "#000000",
      blur: 6,
      offsetX: 2,
      offsetY: 2,
      opacity: 0.4,
    },
    textRotation: 0,
    fontSizeMode: "auto",
  },

  plain_text: {
    fill: "#00000000",
    stroke: "#00ff00",
    strokeWidth: 0,
    opacity: 1,
    fontSize: 20,
    align: "center",
    ...BASE_TEXT,
  },
};

export const TEMPLATE_LABELS: Record<TemplateId, string> = {
  bubble_ellipse: "حوار • بيضاوي",
  bubble_roundrect: "حوار • مستطيل دائري",
  bubble_cloud: "تفكير • سحابة",
  bubble_burst: "حوار • انفجار",
  narration_rect: "سرد • مستطيل",
  narration_roundrect: "سرد • مستطيل دائري",
  caption_box: "توضيح • صندوق",
  scene_label: "نص المشهد • بطاقة",
  signage_label: "لافتة • بطاقة",
  sfx_burst: "مؤثر • انفجار",
  sfx_outline: "مؤثر • حدود",
  plain_text: "نص حر",
};
